version: "3.8"

services:
  postgres:
    container_name: akagi_base_local_db
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=akagi_base_local_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - akagi_app
    restart: unless-stopped
    privileged: true
    command: postgres -c 'max_connections=200'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "akagi_base_local_db"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
       - pg_admin:/var/lib/pgadmin
    networks:
      - akagi_app
    restart: unless-stopped

  redis:
    container_name: akagi_base_local_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - akagi_app
    restart: unless-stopped

networks:
  akagi_app:
    driver: bridge

volumes:
  redis_data:
    driver: local
  pg_data:
    driver: local
  pg_admin:
    driver: local